# Generated by Django 2.2.6 on 2019-11-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='introductions',
            new_name='introduction',
        ),
    ]
