# Generated by Django 2.2.6 on 2019-11-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_userId', models.CharField(max_length=50)),
                ('s_userPw', models.CharField(max_length=20)),
            ],
        ),
    ]
